import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useSession, signIn, signOut } from "next-auth/react"

export default function Home() {
  const {data: session } = useSession()
  if (session){
    return (
      <div className={styles.container}>
        <p>Welcome, {session.user.name}</p>
        <img src={session.user.image} alt="user image" style={{borderRadius: '50px'}} /> <br/>
        <button onClick={() => signOut()} >Sign Out</button>
      </div>
    );
  }else {
    return (
      <div className={styles.container}>
        <p>You are not signed in</p>
        <button onClick={() => signIn()} >Sign In</button>
      </div>
    );

  }



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* {!session && (<button onClick={() => signIn()}>Sign in</button>)}
        {session && <button onClick={() => signOut()} >Sign out({session.user.name})</button> } */}
        

        

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
